const javacoursesdata = [
  {
    name: "Complete Java Programming from Java Basics to Advanced Java",
    teacher: "Muhammad Hamza Abdulrehman",
    platform: "Udemy",
    price: "Free",
    certificate: "Certificate included",
    rating: "4.0",
  },
  {
    name: "Java Programming for Beginners: Become a Java Programmer",
    teacher: "Deepika Khanna",
    platform: "Udemy",
    rating: "4.4",
    price: "Paid",
    certificate: "Certificate included",
  },
  {
    name: "Java for beginners: Step-by-step hands-on guide to Java",
    teacher: "Tetranoodle Team",
    platform: "Udemy",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Java for Beginners: Your Easy Guide to Java Programming",
    teacher: "Video School Online Inc",
    platform: "Udemy",
    price: "Paid",
    certificate: "Certificate included",
    rating: "4.0",
  },
  {
    name: "Java for beginners (Core concepts): Easy course on Java",
    teacher: "Studyeasy Organisation",
    platform: "Udemy",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "ABC of Java (A Perfect Java course for beginner's)",
    platform: "Udemy",
    price: "Paid",
    certificate: "Certificate included",
    rating: "4.6",
    teacher: "",
  },
  {
    name: "Java Basics for Beginners",
    platform: "Udemy",
    price: "Free",
    certificate: "Certificate paid separately",
    rating: "4.5",
    teacher: "",
  },
  {
    name: "Introduction to Java Programming",
    teacher: "Ayeshmantha Madara Wijegunathileke",
    platform: "Udemy",
    rating: "4.2",
    price: "Paid",
    certificate: "Certificate included",
  },
  {
    name: "Java programming for beginners",
    platform: "Udemy",
    price: "Paid",
    certificate: "Certificate included",
    rating: "4.3",
    teacher: "",
  },
  {
    name: "Java Fundamentals for Beginners",
    platform: "Udemy",
    price: "Free",
    certificate: "Certificate paid separately",
    rating: "4.1",
    teacher: "",
  },
  {
    name: "Java For Beginners",
    teacher: "Technology Mania",
    platform: "Skillshare",
    rating: "4.0",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Introduction to Java Programming",
    teacher: "John Thompson",
    platform: "Skillshare",
    rating: "4.3",
    price: "Paid",
    certificate: "Certificate included",
  },
  {
    name: "Java programming for beginners",
    teacher: "Maid Rondić",
    platform: "Skillshare",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Introduction to Java 8",
    teacher: "Matt Speake",
    platform: "Skillshare",
    rating: "4.2",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Java Programming Introduction for Beginners",
    teacher: "Caleb Curry",
    platform: "Skillshare",
    rating: "4.3",
    price: "Paid",
    certificate: "Certificate included",
  },
  {
    name: "Java For Beginners",
    teacher: "Michael Rascon",
    platform: "Skillshare",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "java programming basic syntax",
    teacher: "Yoel Fisher",
    platform: "Skillshare",
    rating: "4.0",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "2021 Edition - A Java Spring Boot Microservices Project for Beginners",
    teacher: "Engineering Tech",
    platform: "Skillshare",
    rating: "4.3",
    price: "Paid",
    certificate: "Certificate included",
  },
  {
    name: "Java Fundamentals: The Java Programming Language",
    teacher: "Rupal Totale",
    platform: "Skillshare",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Java Basics - For Complete Beginners",
    teacher: "Grant Klimaytys",
    platform: "Skillshare",
    rating: "4.4",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Introduction to Java",
    platform: "Coursera",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate included",
    teacher: "",
  },
  {
    name: "Java Class Library",
    platform: "Coursera",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate paid separately",
    teacher: "",
  },
  {
    name: "Object-Oriented Hierarchies in Java",
    platform: "Coursera",
    rating: "4.2",
    price: "Paid",
    certificate: "Certificate included",
    teacher: "",
  },
  {
    name: "Parallel Programming in Java",
    teacher: "Vivek Sarkar",
    platform: "Coursera",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Concurrent Programming in Java",
    teacher: "Vivek Sarkar",
    platform: "Coursera",
    rating: "4.2",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Distributed Programming in Java",
    teacher: "Vivek Sarkar",
    platform: "Coursera",
    rating: "4.3",
    price: "Paid",
    certificate: "Certificate included",
  },
  {
    name: "Introduction to Software Testing",
    teacher: "Sanjai Rayadurgam",
    platform: "Coursera",
    rating: "4.0",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Introduction to Automated Analysis",
    teacher: "Kevin Wendt",
    platform: "Coursera",
    rating: "3.9",
    price: "Paid",
    certificate: "Certificate included",
  },
  {
    name: "Java Programming: Principles of Software Design",
    teacher: "Susan H. Rodger",
    platform: "Coursera",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Web Development with Java Spring Framework",
    platform: "Coursera",
    rating: "3.8",
    price: "Free",
    certificate: "Certificate paid separately",
    teacher: "",
  },
];

module.exports = javacoursesdata;
