const jscoursesdata = [
  {
    name: "JavaScript Introduction to Object Oriented JavaScript",
    teacher: "Laurence Svekis",
    platform: "Udemy",
    rating: "4.2",
    certificate: "Certificate included",
    price: "Free",
  },
  {
    name: "Java Script for Beginners",
    teacher: "A. Obaidi",
    platform: "Udemy",
    rating: "4.2",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "JavaScript for Beginners - The Complete introduction to JS",
    teacher: "Eden Marco",
    platform: "Udemy",
    price: "Free",
    certificate: "Certificate paid separately",
    rating: "4.6",
  },
  {
    name: "Basics of JavaScript coding",
    teacher: "Laurence Svekis",
    platform: "Udemy",
    rating: "4.4",
    certificate: "Certificate included",
    price: "Free",
  },
  {
    name: "Intro to JavaScript APIs",
    platform: "Udemy",
    certificate: "Certificate included",
    price: "Paid",
    rating: "4.2",
    teacher: "",
  },
  {
    name: "JavaScript Basics for Beginners",
    teacher: "Mosh Hamedani",
    platform: "Udemy",
    rating: "4.5",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Introduction to JavaScript Development",
    teacher: "Refactoru Llc",
    platform: "Udemy",
    rating: "4.5",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "GraphQL for beginners with JavaScript",
    teacher: "James Moore",
    platform: "Udemy",
    rating: "4.5",
    certificate: "Certificate included",
    price: "Free",
  },
  {
    name: "Learn Vue 1 JS introduction to simple reactive JavaScript",
    teacher: "Laurence Svekis",
    platform: "Udemy",
    rating: "4.2",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "A Gentle Introduction To JavaScript For Beginners",
    teacher: "Charlie Chiarelli",
    platform: "Udemy",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "JavaScript tutorial for beginners - JavaScript complete course",
    teacher: "Abdull Waheed",
    platform: "Skillshare",
    rating: "4.0",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Basics of JavaScript coding",
    teacher: "Laurence Svekis",
    platform: "Skillshare",
    rating: "4.2",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Basics of programming with javascript",
    platform: "Skillshare",
    certificate: "Certificate included",
    price: "Free",
    rating: "4.1",
    teacher: "",
  },
  {
    name: "Javascript Basics in Hindi||Urdu",
    teacher: "Programmer Kushal",
    platform: "Skillshare",
    rating: "4.2",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "JavaScript For Beginners: A Complete Course",
    platform: "Skillshare",
    certificate: "Certificate included",
    price: "Paid",
    rating: "4.0",
    teacher: "",
  },
  {
    name: "Introduction to NodeJS: Back-End JavaScript",
    teacher: "Keegan Francis",
    platform: "Skillshare",
    rating: "4.2",
    certificate: "Certificate included",
    price: "Free",
  },
  {
    name: "javascript megacourse from basic and beginner to advanced with two real world javascript programming",
    teacher: "Adrien Thomas",
    platform: "Skillshare",
    rating: "4.2",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Asynchronous Javascript From Zero To Hero",
    teacher: "Islam Elgaedy",
    platform: "Skillshare",
    rating: "4.2",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "JavaScript the Basics for Beginners- Section 8: ES6",
    teacher: "Rob Merrill",
    platform: "Skillshare",
    rating: "4.3",
    certificate: "Certificate included",
    price: "Free",
  },
  {
    name: "JavaScript the Basics for Beginners- Section 2: Objects",
    teacher: "Rob Merrill",
    platform: "Skillshare",
    rating: "4.4",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Responsive Website Basics: Code with HTML, CSS, and JavaScript",
    teacher: "Dr Matthew Yee-King",
    platform: "Coursera",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Introduction to Meteor.js Development",
    teacher: "Dr Matthew Yee-King",
    platform: "Coursera",
    rating: "4.5",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Introduction to Cloud Development with HTML, CSS, JavaScript",
    teacher: "Upkar Lidder",
    platform: "Coursera",
    rating: "4.1",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Introduction to Web Development with HTML, CSS, JavaScript",
    teacher: "Upkar Lidder",
    platform: "Coursera",
    price: "Free",
    certificate: "Certificate paid separately",
    rating: "4.3",
  },
  {
    name: "Front-End JavaScript Frameworks: Angular",
    teacher: "Jogesh K. Muppala",
    platform: "Coursera",
    rating: "4.4",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Programming Foundations with JavaScript, HTML and CSS",
    teacher: "Susan H. Rodger",
    platform: "Coursera",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Web Application Development with JavaScript and MongoDB",
    teacher: "Dr Matthew Yee-King",
    platform: "Coursera",
    rating: "4.5",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Introduction to CSS3",
    teacher: "Colleen van Lent, Ph.D.",
    platform: "Coursera",
    rating: "4.6",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Front-End Web Development with React",
    teacher: "Jogesh K. Muppala",
    platform: "Coursera",
    rating: "4.4",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Responsive Web Design",
    teacher: "Dr Mick Grierson",
    platform: "Coursera",
    rating: "4.3",
    certificate: "Certificate included",
    price: "Paid",
  },
];

module.exports = jscoursesdata;
