const pythoncoursesdata = [
  {
    name: "Python Tutorial - Python for Beginners",
    teacher: "Venkata Adithya Kencham",
    platform: "Udemy",
    price: "Free",
    certificate: "Certificate paid separately",
    rating: "4.1",
  },
  {
    name: "Python For Beginners",
    platform: "Udemy",
    price: "Free",
    certificate: "Certificate paid separately",
    rating: "4.1",
    teacher: "",
  },
  {
    name: "Python for Beginners",
    teacher: "Mark Lassoff",
    platform: "Udemy",
    rating: "4.6",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Python for Beginners",
    platform: "Udemy",
    certificate: "Certificate included",
    price: "Paid",
    rating: "3.9",
    teacher: "",
  },
  {
    name: "Introduction to python",
    teacher: "Prof. Venkata L Raju Vatsavayi",
    platform: "Udemy",
    certificate: "Certificate included",
    price: "Paid",
    rating: "3.9",
  },
  {
    name: "Intro to Python",
    teacher: "Stem Helper",
    platform: "Udemy",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Python for Beginners",
    platform: "Udemy",
    certificate: "Certificate included",
    price: "Paid",
    rating: "4.2",
    teacher: "",
  },
  {
    name: "Python for New learners: Introduction to python programming",
    teacher: "Adeel Ahmad",
    platform: "Udemy",
    rating: "4.8",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Python in 3 Hours: Python Programming for Beginners",
    teacher: "Ajay R Warrier",
    platform: "Udemy",
    rating: "4.2",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Hello Python - Python Programming for Beginners",
    teacher: "Rob Merrill",
    platform: "Udemy",
    rating: "4.5",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Python 3: Programming in Python for Beginners",
    teacher: "Arkadiusz Włodarczyk",
    platform: "Skillshare",
    rating: "4.5",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Python Programming: Learn basics of Python",
    platform: "Skillshare",
    price: "Free",
    certificate: "Certificate paid separately",
    rating: "4.1",
    teacher: "",
  },
  {
    name: "Introduction to Python",
    platform: "Skillshare",
    certificate: "Certificate included",
    price: "Paid",
    rating: "4.6",
    teacher: "",
  },
  {
    name: "Python Programming for Beginners: Learn Python in 3 Hours",
    teacher: "Prof. Bunny",
    platform: "Skillshare",
    rating: "4.2",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Python Tutorial for Beginners",
    teacher: "Kisilu Justus",
    platform: "Skillshare",
    rating: "4.1",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Python Programming for Beginners",
    teacher: "Bahbouh Code",
    platform: "Skillshare",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Python programming for beginners",
    teacher: "Fala francês com Jérôme",
    platform: "Skillshare",
    rating: "4.1",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Python Tutorial for beginners",
    teacher: "Shivprasad Koirala",
    platform: "Skillshare",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Python Code for Beginners",
    teacher: "Grant 'Angular' K",
    platform: "Skillshare",
    rating: "4.0",
    certificate: "Certificate included",
    price: "Paid",
  },
  {
    name: "Python 3 Programming: Your Guide to Basic Python Programming for Beginners",
    teacher: "Matthew Dewey",
    platform: "Skillshare",
    rating: "4.2",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Introduction to Data Analytics",
    platform: "Coursera",
    price: "Paid",
    certificate: "Certificate included",
    rating: "4.2",
    teacher: "",
  },
  {
    name: "Introduction to Self-Driving Cars",
    teacher: "Steven Waslander",
    platform: "Coursera",
    rating: "4.4",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Advanced Django: Introduction to Django Rest Framework",
    platform: "Coursera",
    price: "Paid",
    certificate: "Certificate included",
    rating: "4.2",
    teacher: "",
  },
  {
    name: "Data Processing Using Python",
    teacher: "ZHANG Li",
    platform: "Coursera",
    rating: "4.0",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Python and Statistics for Financial Analysis",
    teacher: "Xuhu Wan",
    platform: "Coursera",
    rating: "4.1",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Introduction to Accounting Data Analytics and Visualization",
    teacher: "Ronald Guymon",
    platform: "Coursera",
    rating: "4.5",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Introduction to Reproducibility in Cancer Informatics",
    platform: "Coursera",
    price: "Paid",
    certificate: "Certificate included",
    rating: "4.3",
    teacher: "",
  },
  {
    name: "Python for Data Science, AI & Development",
    teacher: "Joseph Santarcangelo",
    platform: "Coursera",
    rating: "4.3",
    price: "Free",
    certificate: "Certificate included",
  },
  {
    name: "Problem Solving, Python Programming, and Video Games",
    teacher: "Duane Szafron",
    platform: "Coursera",
    rating: "4.0",
    price: "Free",
    certificate: "Certificate paid separately",
  },
  {
    name: "Database Clients",
    platform: "Coursera",
    price: "Free",
    certificate: "Certificate included",
    rating: "4.3",
    teacher: "",
  },
];

module.exports = pythoncoursesdata;
